spring.application.name=demo

# Conexión PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/premierleague
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Para ver en consola
spring.jpa.show-sql=true